name: Check feed Service
on:
  pull_request:
    branches:
      - develop
    paths:
      - 'feed-service/**/*'  # path for the feed service folder Whenever you will make changes in this folder. Checks will trigger 
  push:
    branches:
      - develop
    paths:
      - 'feed-service/**/*'  # path for the feed service folder Whenever you will make changes in this folder. Checks will trigger

env:
  ORG: knoldus Inc
  PROJECT_NAME: knoldus-leaderboard
  AUTHOR: MuZakkir Saifi(muzakkirsaifi123)


jobs:
  build:
    name: Checks for the Feed Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        working-directory: feed-service/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FEED }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        run: mvn clean verify sonar:sonar  -Dsonar.projectKey=${{ secrets.PROJECT_KEY_FEED }}